### PR TITLE
Docker virtual network

### PR DESCRIPTION
**Pull request by Lebski**
Make the production independent of host system 

- Removed host network from docker-compose.prod.yaml
- Removed exposed ports 
- Added container references in nginx.prod.conf

### CODE REVIEW

**Comment by Lebski** [comment]
To your concerns mentioned in #19 

Postgres: Oh sure, you are right about that. I removed it after testing. 

Network: I thought the performance penalty would only affect encrypted communication. If people reach the point when they need IPSEC tunnels between their nodes, they should probably move away from docker compose and swarm to Kubernetes, anyways. And then it could be quite handy to have an alias. But that's just the experience I've had, could be wrong.

**Comment by karlkeefer** [comment]
Yeah honestly it hasn't affected me at all, but multiple people in the hn thread mentioned that you need host networking to avoid network bottlenecks.

No idea how much that is cargo culting or not... Is there a *problem* using host networking in production?

**Comment by Lebski** [comment]
Probably it's just a matter of taste. I prefer maintainability over performance in such an early stage. 
I would guess that before the performance issues will occur, people have already included the services into their own eco system.

**Comment by karlkeefer** [comment]
I'm convinced :) Rolled as a separate PR to make some more tweaks to `depends_on` in dev, keep port declarations in place, etc.

Thank you!

**Pull request closed without merging**
